# Generated by Django 4.2.16 on 2026-09-23 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('question_type', models.CharField(choices=[('number', '数字推理'), ('figure', '图形推理'), ('logic', '逻辑判断'), ('analogy', '类比推理'), ('deduction', '演绎推理')], max_length=32)),
                ('difficulty', models.CharField(max_length=16)),
                ('stem', models.TextField()),
                ('answer', models.CharField(max_length=32)),
                ('explanation', models.TextField()),
                ('knowledge', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='questions/')),
            ],
        ),
        migrations.CreateModel(
            name='PaperSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_no', models.PositiveIntegerField(unique=True, verbose_name='试卷编号')),
                ('requested_difficulty', models.CharField(max_length=16, verbose_name='选定难度')),
                ('requested_amount', models.PositiveIntegerField(verbose_name='选定题量')),
                ('actual_amount', models.PositiveIntegerField(verbose_name='实际题量')),
                ('questions', models.JSONField(verbose_name='题目顺序快照')),
                ('type_quota', models.JSONField(default=dict, verbose_name='各题型目标配额')),
                ('type_actual', models.JSONField(default=dict, verbose_name='各题型实际题量')),
                ('type_gaps', models.JSONField(default=dict, verbose_name='各题型缺口')),
                ('replacements', models.JSONField(default=list, verbose_name='相邻难度补入明细')),
                ('replacement_count', models.PositiveIntegerField(default=0, verbose_name='补入题数')),
                ('replacement_note', models.CharField(blank=True, max_length=255, verbose_name='替换说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-paper_no'],
            },
        ),
        migrations.CreateModel(
            name='WrongBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistakes', models.PositiveIntegerField(default=1)),
                ('favorited', models.BooleanField(default=False)),
                ('last_practiced_at', models.DateField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.logicquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
